model:
  target: image_synthesis.modeling.model.inpainting_model.InpaintingModel
  params:
    mode: 'inpainitng'
    codec_path: ./output/experiments/paris/fdm_tuning/checkpoint/last.pth
    generator_path: ./output/experiments/paris/transformer/checkpoint/last.pth
    content_codec_config:
      target: image_synthesis.modeling.codecs.image_codec.patch_vqgan.PatchVQGAN
      params:
        trainable: False
        quantizer_config:
          target: image_synthesis.modeling.codecs.image_codec.vector_quantizer.VectorQuantizer
          params:
            n_e: 1024
            e_dim: 256
            masked_embed_start: 512
            embed_ema: True
            get_embed_type: retrive
            distance_type: euclidean
        encoder_config: 
          target: image_synthesis.modeling.codecs.image_codec.encoder.PatchEncoder
          params:
            in_ch: 3
            res_ch: 256
            out_ch: 256
            stride: 8
        decoder_config:
          target: image_synthesis.modeling.codecs.image_codec.decoder.PatchDecoder
          params:
            in_ch: 256
            out_ch: 3
            res_ch: 256
    fdm_config:
      target: image_synthesis.modeling.modules.FDM.fdm.FDM
      params:
        e_dim: 256
    generator_config:
      target: image_synthesis.modeling.vector_predictor.transformer.MaskedImageInpaintingTransformer
      params:
        n_layer: 35
        content_seq_len: 1024
        n_embd: 512 # embedding dim
        n_head: 8

        num_token: 512

        embd_pdrop: 0.0
        attn_pdrop: 0.0
        resid_pdrop: 0.0
        attn_content_with_mask: False
        mlp_hidden_times: 4
        block_activate: GELU2
        random_quantize: 0.3
        weight_decay: 0.01